# Generated by Django 3.0 on 2020-10-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drywaste',
            fields=[
                ('category', models.CharField(max_length=200)),
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('sp_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sp_on_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
