# Generated by Django 3.0 on 2020-10-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaneCordinator',
            fields=[
                ('cordinator_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('mentor_name', models.CharField(max_length=200)),
                ('attendants_name', models.CharField(max_length=200)),
                ('attendants_lane_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lanedetails',
            fields=[
                ('lane_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('num_houses_lane', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tracksheet',
            fields=[
                ('num_houses_reached', models.IntegerField()),
                ('num_houses_doing_segg', models.IntegerField()),
                ('num_houses_giving_mixwaste', models.IntegerField()),
                ('drywaste_bf', models.IntegerField()),
                ('drywaste_af', models.IntegerField()),
                ('wetwaste_bf', models.IntegerField()),
                ('wetwaste_af', models.IntegerField()),
                ('lane_name', models.CharField(max_length=200)),
                ('num_attendants', models.IntegerField()),
                ('attendants_name', models.CharField(max_length=200)),
                ('time_of_visit_morning', models.CharField(max_length=50)),
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
