# Generated by Django 3.0 on 2020-10-08 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('swk', '0002_lanecordinator_lanedetails_tracksheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='TracksheetModel',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='Drywaste',
        ),
        migrations.DeleteModel(
            name='LaneCordinator',
        ),
        migrations.DeleteModel(
            name='Lanedetails',
        ),
        migrations.AlterField(
            model_name='tracksheet',
            name='attendants_name',
            field=models.CharField(choices=[('Amrapali', 'Amrapali'), ('Jana pote', 'Jana pote'), ('Kaushalya', 'Kaushalya'), ('Parvati', 'Parvati'), ('Sakuntala', 'Sakuntala'), ('Asha', 'Asha')], default='Amrapali', max_length=100),
        ),
        migrations.AlterField(
            model_name='tracksheet',
            name='time_of_visit_morning',
            field=models.CharField(choices=[('7:30am - 8:30 am', 'Morning'), ('7:30pm - 8:30 pm', 'Evening')], default='Morning', max_length=100),
        ),
    ]
