# Generated by Django 3.0 on 2020-10-14 07:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('swk', '0003_auto_20201008_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='tracksheet',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tracksheet',
            name='lane_name',
            field=models.CharField(choices=[('Waras lane to Hira Seth chawl', 'Waras lane - Hira Seth chawl'), ('Navneet Lane to Tare Galli', 'Navneet Lane - Tare Galli'), ('BhandarWada to Amar Prem Chowk', 'BhandarWada - Amar Prem Chowk'), ('Shankar Mandir to Bhagat Galli ', 'Shankar Mandir - Bhagat Galli '), ('Gonta Galli to Kranti Galli', 'Gonta Galli - Kranti Galli'), ('Kranti Galli to Navjeevan Chauk', 'Kranti Galli - Navjeevan Chauk'), ('Pakhari Galli ', 'Pakhari Galli '), ('Vada pav Galli to Fish market', 'Vada pav Galli - Fish market'), ('Payari', 'Payari'), ('Sonapur to Dukkur Galli', 'Sonapur - Dukkur Galli'), ('Dukkur to Taak Galli', 'Dukkur - Taak Galli'), ('Nagobacha Ghumat to Achanak', 'Nagobacha Ghumat - Achanak'), ('Golfadevi', 'Golfadevi')], max_length=200),
        ),
        migrations.AlterField(
            model_name='tracksheet',
            name='num_attendants',
            field=models.IntegerField(default=2),
        ),
    ]
