# Generated by Django 3.0 on 2020-10-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0004_auto_20201014_0745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracksheet',
            old_name='attendants_name',
            new_name='first_attendants_name',
        ),
        migrations.AddField(
            model_name='tracksheet',
            name='second_first_attendants_name',
            field=models.CharField(choices=[('Amrapali', 'Amrapali'), ('Jana pote', 'Jana pote'), ('Kaushalya', 'Kaushalya'), ('Parvati', 'Parvati'), ('Sakuntala', 'Sakuntala'), ('Asha', 'Asha')], default='Jana pote', max_length=100),
        ),
        migrations.AlterField(
            model_name='tracksheet',
            name='num_houses_reached',
            field=models.IntegerField(default=100),
        ),
    ]
