# Generated by Django 3.0 on 2020-10-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0005_auto_20201020_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracksheet',
            old_name='second_first_attendants_name',
            new_name='second_attendants_name',
        ),
        migrations.RenameField(
            model_name='tracksheet',
            old_name='time_of_visit_morning',
            new_name='time_of_visit',
        ),
        migrations.AlterField(
            model_name='tracksheet',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
