# Generated by Django 3.1.2 on 2020-10-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0004_auto_20201015_0556'),
        ('swk', '0006_auto_20201022_0703'),
    ]

    operations = [
    ]
